
project_id = "pxqcvlhxoqipwgwplrpx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions]
[functions.newsletter-subscribe]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = true
