// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxqcvlhxoqipwgwplrpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4cWN2bGh4b3FpcHdnd3BscnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTQxNjIsImV4cCI6MjA1OTE5MDE2Mn0.r9C6IJOSSlVE7pAzLIyyfKnMwMyFZHybRy6JGFrTk7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);